import { ExportOptions } from '../components/project/export-project-modal'
import { Project, Item, Part, PartGroup } from '../types'
import { PRESENTATION_THEMES, getThemeCSS } from './presentation-themes'

export class HTMLPresentationGenerator {
  private options: ExportOptions
  private project: Project

  constructor(project: Project, options: ExportOptions) {
    this.options = options
    this.project = project
  }

  generate(): string {
    // Get the selected theme
    const selectedTheme = PRESENTATION_THEMES.find(theme => theme.name === this.options.theme) || PRESENTATION_THEMES[0]
    
    const html = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${this.options.customTitle || this.project.title}</title>
    <style>
        ${getThemeCSS(selectedTheme)}
        
        /* Base styles */
        body {
            margin: 0;
            padding: 0;
        }
        
        .slide {
            width: 100%;
            min-height: 100vh;
            padding: 40px;
            box-sizing: border-box;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            text-align: center;
            page-break-after: always;
        }
        
        .slide:last-child {
            page-break-after: avoid;
        }
        
        .content-slide {
            background: var(--card);
        }
        
        .slide-title {
            font-size: 2.5em;
            font-weight: bold;
            margin-bottom: 20px;
            color: inherit;
        }
        
        .slide-subtitle {
            font-size: 1.2em;
            margin-bottom: 30px;
            opacity: 0.9;
        }
        
        .slide-content {
            font-size: 1.1em;
            line-height: 1.6;
            max-width: 800px;
        }
        
        .project-info {
            background: rgba(255, 255, 255, 0.1);
            padding: 20px;
            border-radius: var(--border-radius);
            margin-top: 20px;
        }
        
        .image-container {
            max-width: 600px;
            margin: 20px auto;
        }
        
        .parts-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 20px;
            margin-top: 20px;
        }
        
        .part-details {
            font-size: 0.9em;
            color: var(--text-light);
        }
        
        .footer {
            position: fixed;
            bottom: 20px;
            right: 20px;
            background: rgba(0, 0, 0, 0.7);
            color: white;
            padding: 10px 15px;
            border-radius: 20px;
            font-size: 0.8em;
        }
        
        @media print {
            .slide {
                page-break-after: always;
                min-height: 100vh;
            }
            .footer {
                display: none;
            }
        }
    </style>
</head>
<body>
    ${this.generateSlides()}
    <div class="footer">
        Generated by Core Home Render Portal
    </div>
</body>
</html>`

    return html
  }

  private generateSlides(): string {
    let slides = ''

    // Title Slide
    if (this.options.includeProjectOverview) {
      slides += this.generateTitleSlide()
      slides += this.generateOverviewSlide()
    }

    // Image Slides
    if (this.options.includeAnnotatedImages) {
      slides += this.generateImageSlides()
    }

    // Part Details
    if (this.options.includePartDetails) {
      slides += this.generatePartDetailsSlides()
    }

    // Groups
    if (this.options.includePartGroups) {
      slides += this.generateGroupSummarySlide()
    }

    // Team Info
    if (this.options.includeTeamInfo) {
      slides += this.generateTeamInfoSlide()
    }

    // Notes
    if (this.options.includeNotes) {
      slides += this.generateNotesSlide()
    }

    return slides
  }

  private generateTitleSlide(): string {
    return `
    <div class="slide title-slide">
        <h1 class="slide-title">${this.options.customTitle || this.project.title}</h1>
        <div class="slide-subtitle">Generated on ${new Date().toLocaleDateString()}</div>
        ${this.project.retailer ? `<div class="project-info">Retailer: ${this.project.retailer}</div>` : ''}
    </div>`
  }

  private generateOverviewSlide(): string {
    const itemCount = this.project.items?.length || 0
    const partCount = this.project.items?.[0]?.parts?.length || 0
    const groupCount = this.project.items?.[0]?.groups?.length || 0

    return `
    <div class="slide content-slide">
        <h2 class="slide-title">Project Overview</h2>
        <div class="slide-content">
            <p><strong>Project Name:</strong> ${this.project.title}</p>
            <p><strong>Retailer:</strong> ${this.project.retailer || 'Not specified'}</p>
            <p><strong>Created:</strong> ${new Date(this.project.created_at).toLocaleDateString()}</p>
            <p><strong>Last Updated:</strong> ${new Date(this.project.updated_at).toLocaleDateString()}</p>
            <p><strong>Items:</strong> ${itemCount}</p>
            <p><strong>Total Parts:</strong> ${partCount}</p>
            ${groupCount > 0 ? `<p><strong>Part Groups:</strong> ${groupCount}</p>` : ''}
        </div>
    </div>`
  }

  private generateImageSlides(): string {
    if (!this.project.items || this.project.items.length === 0) return ''

    let slides = ''
    for (const item of this.project.items) {
      if (item.hero_image) {
        slides += `
        <div class="slide content-slide">
            <h2 class="slide-title">Item: ${item.name || 'Unnamed Item'}</h2>
            <div class="image-container">
                <img src="${item.hero_image}" alt="${item.name || 'Item'}" class="project-image">
            </div>
            ${this.generatePartsList(item)}
        </div>`
      }
    }
    return slides
  }

  private generatePartsList(item: Item): string {
    if (!item.parts || item.parts.length === 0) return ''

    const partsList = item.parts.map(part => 
      `<li><strong>${part.name || 'Unnamed'}</strong> (${part.finish || 'No finish'})</li>`
    ).join('')

    return `
    <div class="slide-content">
        <h3>Parts (${item.parts.length})</h3>
        <ul style="text-align: left; max-width: 400px; margin: 0 auto;">
            ${partsList}
        </ul>
    </div>`
  }

  private generatePartDetailsSlides(): string {
    if (!this.project.items || this.project.items.length === 0) return ''

    const item = this.project.items[0]
    if (!item.parts || item.parts.length === 0) return ''

    // Group parts into slides (6 per slide)
    const partsPerSlide = 6
    const partSlides = Math.ceil(item.parts.length / partsPerSlide)
    let slides = ''

    for (let i = 0; i < partSlides; i++) {
      const startIndex = i * partsPerSlide
      const endIndex = Math.min(startIndex + partsPerSlide, item.parts.length)
      const slideParts = item.parts.slice(startIndex, endIndex)

      slides += `
      <div class="slide content-slide">
          <h2 class="slide-title">Part Specifications (${startIndex + 1}-${endIndex})</h2>
          <div class="parts-grid">
              ${slideParts.map(part => this.generatePartCard(part, item.groups)).join('')}
          </div>
      </div>`
    }

    return slides
  }

  private generatePartCard(part: Part, groups?: PartGroup[]): string {
    const groupName = groups?.find(g => g.id === part.groupId)?.name || 'None'
    
    return `
    <div class="part-card">
        <div class="part-name">${part.name || 'Unnamed'}</div>
        <div class="part-details">
            <p><strong>Finish:</strong> ${part.finish || 'Not specified'}</p>
            <p><strong>Color:</strong> 
                <span style="display: inline-block; width: 20px; height: 20px; background-color: ${part.color}; border: 1px solid #ccc; border-radius: 3px; vertical-align: middle; margin-right: 5px;"></span>
                ${part.color || 'Not specified'}
            </p>
            <p><strong>Texture:</strong> ${part.texture || 'Not specified'}</p>
            <p><strong>Group:</strong> ${groupName}</p>
            ${part.notes ? `<p><strong>Notes:</strong> ${part.notes}</p>` : ''}
        </div>
    </div>`
  }

  private generateGroupSummarySlide(): string {
    if (!this.project.items || this.project.items.length === 0) return ''

    const item = this.project.items[0]
    if (!item.groups || item.groups.length === 0) return ''

    const groupInfo = item.groups.map(group => {
      const groupParts = item.parts?.filter(part => part.groupId === group.id) || []
      return `<li><strong>${group.name}</strong> (${groupParts.length} parts)</li>`
    }).join('')

    return `
    <div class="slide content-slide">
        <h2 class="slide-title">Part Grouping & Organization</h2>
        <div class="slide-content">
            <h3>Groups:</h3>
            <ul style="text-align: left; max-width: 400px; margin: 0 auto;">
                ${groupInfo}
            </ul>
        </div>
    </div>`
  }

  private generateTeamInfoSlide(): string {
    return `
    <div class="slide content-slide">
        <h2 class="slide-title">Team & Collaboration</h2>
        <div class="slide-content">
            <p><strong>Project Owner:</strong> ${this.project.user_id}</p>
            <p><strong>Created:</strong> ${new Date(this.project.created_at).toLocaleDateString()}</p>
            <p><strong>Last Updated:</strong> ${new Date(this.project.updated_at).toLocaleDateString()}</p>
            <div class="group-info">
                <p><em>Note: This project may have collaborators with various permission levels</em></p>
            </div>
        </div>
    </div>`
  }

  private generateNotesSlide(): string {
    return `
    <div class="slide content-slide">
        <h2 class="slide-title">Project Notes & Next Steps</h2>
        <div class="slide-content">
            <p>Add your project notes, next steps, and action items here.</p>
            <div class="group-info" style="margin-top: 40px;">
                <p><strong>Action Items:</strong></p>
                <ul style="text-align: left; max-width: 400px; margin: 0 auto;">
                    <li>Review project specifications</li>
                    <li>Finalize part details</li>
                    <li>Schedule project review</li>
                    <li>Prepare for production</li>
                </ul>
            </div>
        </div>
    </div>`
  }
}

export function generateHTMLPresentation(
  project: Project,
  options: ExportOptions
): string {
  const generator = new HTMLPresentationGenerator(project, options)
  return generator.generate()
}
